# Generated by Django 4.2.4 on 2023-09-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('login', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
            ],
        ),
    ]
